decoration {
     rounding = 25
     rounding_power = 10

     # Change transparency of focused and unfocused wi>
     active_opacity = 0.98
     inactive_opacity = 0.97

     shadow {
         enabled = true
         range = 4
         render_power = 3
         color = rgba(1a1a1aee)
     }

     # https://wiki.hypr.land/Configuring/Variables/#b>
     blur {
         enabled = true
         size = 3
         passes = 1

         vibrancy = 0.1696
     }
 }
