exec-once = swww-daemon
exec-once = waybar
exec-once = swaync
exec-once = hyprctl setcursor Capitaine-Cursors-Gruvbox 24
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = hyprlock
