general {
     gaps_in = 10
     gaps_out = 30
     
     border_size = 1
     
     # https://wiki.hypr.land/Configuring/Variables/#v>
     col.active_border = rgba(fd6883aa)
     col.inactive_border = rgba(fd6883aa)
     
     # Set to true enable resizing windows by clicking>
     resize_on_border = false

     # Please see https://wiki.hypr.land/Configuring/T>
     allow_tearing = false

     layout = dwindle
}
