general {
    lock_cmd = pidof hyprlock || hyprlock       # Kilit komutu
    before_sleep_cmd = loginctl lock-session    # Uykuya geçmeden önce kilitle
    after_sleep_cmd = hyprctl dispatch dpms on  # Uyanınca ekranı aç
}

listener {
    timeout = 300                                # 5 dakika (300sn)
    on-timeout = loginctl lock-session           # Ekranı kilitle
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off       # Ekranı tamamen kapat (Güç tasarrufu)
    on-resume = hyprctl dispatch dpms on         # Geri gelince aç
}
