source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/execs.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/permission.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windowrules.conf
