dwindle {
    pseudotile = true
    preserve_split = true
}

# Hatalı olan kısım burasıydı, düzelttik:
master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

# --- PENCERE KURALLARI ---

# Genel Kurallar
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# --- WALLPAPER SEÇİCİ KURALI ---
# Bu kuralın çalışması için terminalin "class" değeri "wallpaper_selector" olmalı.
# --- Waypaper Görünüm Ayarları ---
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$
windowrulev2 = size 800 500, class:^(waypaper)$
windowrulev2 = pin, class:^(waypaper)$ # Her workspace'te görünsün

# --- Tema Modu Toggle Penceresi ---
windowrulev2 = float, title:^(Tema Modu)$
windowrulev2 = size 220 120, title:^(Tema Modu)$
windowrulev2 = move 100%-230 80, title:^(Tema Modu)$
windowrulev2 = pin, title:^(Tema Modu)$
windowrulev2 = stayfocused, title:^(Tema Modu)$
