# kishi_settings/theme_generator.py
import os
import subprocess
from pathlib import Path


class ThemeGenerator:
    """Wallpaper'dan çıkarılan renk paletinden tema dosyaları oluşturur"""

    def __init__(self, palette, wallpaper_name, light_mode=False):
        """
        Args:
            palette: Renk paleti dict (bg, fg, red, orange, yellow, green, aqua, blue, purple, bg0, bg1, bg2)
            wallpaper_name: Wallpaper dosya adı
            light_mode: Light mode aktif mi (True/False)
        """
        self.palette = palette
        self.wallpaper_name = wallpaper_name
        self.light_mode = light_mode
        self.config_path = os.path.expanduser("~/.config")
        self.theme_name = f"wallpaper_{self._sanitize_name(wallpaper_name)}"

    def _sanitize_name(self, name):
        """Dosya adını temizle"""
        # Uzantıyı kaldır
        name = os.path.splitext(name)[0]
        # Boşlukları ve özel karakterleri değiştir
        return name.replace(' ', '_').replace('-', '_').lower()

    def generate_hyprland_colors(self):
        """Hyprland colors.conf içeriğini oluştur"""
        return f"""# Generated from wallpaper: {self.wallpaper_name}
# Auto-generated by Kishi Settings

general {{
    col.active_border = rgb({self.palette['blue'][1:]}) rgb({self.palette['purple'][1:]}) 45deg
    col.inactive_border = rgb({self.palette['bg2'][1:]})
}}

# Gruvbox-style colors from wallpaper
$bg = {self.palette['bg']}
$bg0 = {self.palette['bg0']}
$bg1 = {self.palette['bg1']}
$bg2 = {self.palette['bg2']}
$fg = {self.palette['fg']}

$red = {self.palette['red']}
$orange = {self.palette['orange']}
$yellow = {self.palette['yellow']}
$green = {self.palette['green']}
$aqua = {self.palette['aqua']}
$blue = {self.palette['blue']}
$purple = {self.palette['purple']}
"""

    def generate_waybar_theme(self):
        """Waybar style.css oluştur"""
        return f"""/* Generated from wallpaper: {self.wallpaper_name} */
/* Auto-generated by Kishi Settings */

@define-color bg {self.palette['bg']};
@define-color bg0 {self.palette['bg0']};
@define-color bg1 {self.palette['bg1']};
@define-color bg2 {self.palette['bg2']};
@define-color fg {self.palette['fg']};
@define-color red {self.palette['red']};
@define-color orange {self.palette['orange']};
@define-color yellow {self.palette['yellow']};
@define-color green {self.palette['green']};
@define-color aqua {self.palette['aqua']};
@define-color blue {self.palette['blue']};
@define-color purple {self.palette['purple']};

* {{
    font-family: "JetBrainsMono Nerd Font";
    font-size: 13px;
    min-height: 0;
}}

window#waybar {{
    background: @bg;
    color: @fg;
}}

/* Workspaces */
#workspaces button {{
    background: @bg1;
    color: @fg;
    border-radius: 8px;
    margin: 5px 3px;
    padding: 0 10px;
}}

#workspaces button.active {{
    background: @blue;
    color: @bg;
}}

#workspaces button.urgent {{
    background: @red;
    color: @bg;
}}

/* Clock */
#clock {{
    background: @bg1;
    color: @yellow;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

/* Battery */
#battery {{
    background: @bg1;
    color: @green;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

#battery.charging {{
    color: @aqua;
}}

#battery.warning {{
    color: @orange;
}}

#battery.critical {{
    color: @red;
}}

/* Network */
#network {{
    background: @bg1;
    color: @blue;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

/* Pulseaudio */
#pulseaudio {{
    background: @bg1;
    color: @purple;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

/* CPU */
#cpu {{
    background: @bg1;
    color: @orange;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

/* Memory */
#memory {{
    background: @bg1;
    color: @aqua;
    border-radius: 8px;
    padding: 5px 15px;
    margin: 5px;
}}

/* Tray */
#tray {{
    background: @bg1;
    border-radius: 8px;
    padding: 5px 10px;
    margin: 5px;
}}
"""

    def generate_rofi_theme(self):
        """Rofi tema oluştur"""
        return f"""/* Generated from wallpaper: {self.wallpaper_name} */
/* Auto-generated by Kishi Settings */

* {{
    bg: {self.palette['bg']};
    bg-alt: {self.palette['bg1']};
    bg2: {self.palette['bg2']};
    fg: {self.palette['fg']};

    red: {self.palette['red']};
    orange: {self.palette['orange']};
    yellow: {self.palette['yellow']};
    green: {self.palette['green']};
    aqua: {self.palette['aqua']};
    blue: {self.palette['blue']};
    purple: {self.palette['purple']};

    accent: {self.palette['blue']};
    urgent: {self.palette['red']};

    background-color: transparent;
    text-color: @fg;
}}

window {{
    background-color: @bg;
    border: 2px;
    border-color: @accent;
    border-radius: 10px;
    padding: 20px;
}}

inputbar {{
    background-color: @bg-alt;
    text-color: @fg;
    border-radius: 8px;
    padding: 10px;
}}

prompt {{
    text-color: @accent;
}}

entry {{
    text-color: @fg;
}}

listview {{
    background-color: transparent;
    spacing: 5px;
    margin-top: 10px;
}}

element {{
    background-color: transparent;
    text-color: @fg;
    border-radius: 8px;
    padding: 8px;
}}

element selected {{
    background-color: @accent;
    text-color: @bg;
}}

element-icon {{
    size: 24px;
}}

element-text {{
    vertical-align: 0.5;
}}
"""

    def generate_kitty_theme(self):
        """Kitty terminal tema oluştur"""
        return f"""# Generated from wallpaper: {self.wallpaper_name}
# Auto-generated by Kishi Settings

# Background & Foreground
background {self.palette['bg']}
foreground {self.palette['fg']}

# Black
color0  {self.palette['bg']}
color8  {self.palette['bg2']}

# Red
color1  {self.palette['red']}
color9  {self.palette['red']}

# Green
color2  {self.palette['green']}
color10 {self.palette['green']}

# Yellow
color3  {self.palette['yellow']}
color11 {self.palette['yellow']}

# Blue
color4  {self.palette['blue']}
color12 {self.palette['blue']}

# Magenta
color5  {self.palette['purple']}
color13 {self.palette['purple']}

# Cyan
color6  {self.palette['aqua']}
color14 {self.palette['aqua']}

# White
color7  {self.palette['fg']}
color15 {self.palette['fg']}

# Cursor
cursor {self.palette['fg']}
cursor_text_color {self.palette['bg']}

# Selection
selection_background {self.palette['blue']}
selection_foreground {self.palette['bg']}

# Tab bar
active_tab_background {self.palette['blue']}
active_tab_foreground {self.palette['bg']}
inactive_tab_background {self.palette['bg1']}
inactive_tab_foreground {self.palette['fg']}
"""

    def save_hyprland_colors(self):
        """Hyprland colors.conf kaydet"""
        themes_dir = f"{self.config_path}/hypr/themes"
        os.makedirs(themes_dir, exist_ok=True)

        colors_path = f"{themes_dir}/{self.theme_name}_colors.conf"
        with open(colors_path, 'w') as f:
            f.write(self.generate_hyprland_colors())

        print(f"  Hyprland: {colors_path}")
        return colors_path

    def save_waybar_theme(self):
        """Waybar theme kaydet"""
        themes_dir = f"{self.config_path}/waybar/themes"
        os.makedirs(themes_dir, exist_ok=True)

        waybar_path = f"{themes_dir}/{self.theme_name}.css"
        with open(waybar_path, 'w') as f:
            f.write(self.generate_waybar_theme())

        print(f"  Waybar: {waybar_path}")
        return waybar_path

    def save_rofi_theme(self):
        """Rofi theme kaydet"""
        themes_dir = f"{self.config_path}/rofi/themes"
        os.makedirs(themes_dir, exist_ok=True)

        rofi_path = f"{themes_dir}/{self.theme_name}.rasi"
        with open(rofi_path, 'w') as f:
            f.write(self.generate_rofi_theme())

        print(f"  Rofi: {rofi_path}")
        return rofi_path

    def save_kitty_theme(self):
        """Kitty theme kaydet"""
        themes_dir = f"{self.config_path}/kitty/themes"
        os.makedirs(themes_dir, exist_ok=True)

        kitty_path = f"{themes_dir}/{self.theme_name}.conf"
        with open(kitty_path, 'w') as f:
            f.write(self.generate_kitty_theme())

        print(f"  Kitty: {kitty_path}")
        return kitty_path

    def save_all_themes(self):
        """Tüm temaları kaydet"""
        print(f"\n Tema dosyaları kaydediliyor: {self.theme_name}")

        paths = {
            'hyprland': self.save_hyprland_colors(),
            'waybar': self.save_waybar_theme(),
            'rofi': self.save_rofi_theme(),
            'kitty': self.save_kitty_theme()
        }

        print(f" Tüm temalar kaydedildi!\n")
        return paths

    def apply_hyprland_theme(self):
        """Hyprland temasını uygula"""
        colors_path = f"{self.config_path}/hypr/themes/{self.theme_name}_colors.conf"
        hyprland_conf = f"{self.config_path}/hypr/hyprland.conf"

        # hyprland.conf'a source satırı ekle veya güncelle
        source_line = f"source = ~/.config/hypr/themes/{self.theme_name}_colors.conf"

        try:
            # Mevcut config'i oku
            with open(hyprland_conf, 'r') as f:
                content = f.read()

            # Eski wallpaper tema source'unu kaldır
            lines = content.split('\n')
            new_lines = []
            for line in lines:
                if 'source' in line and 'themes/wallpaper_' in line and '_colors.conf' in line:
                    continue  # Eski tema source'unu atla
                new_lines.append(line)

            # Yeni source'u ekle (dosyanın başına)
            new_content = '\n'.join(new_lines)
            if source_line not in new_content:
                # İlk source satırından sonra ekle
                insert_pos = new_content.find('source')
                if insert_pos != -1:
                    end_of_line = new_content.find('\n', insert_pos)
                    new_content = new_content[:end_of_line+1] + source_line + '\n' + new_content[end_of_line+1:]
                else:
                    new_content = source_line + '\n' + new_content

            # Kaydet
            with open(hyprland_conf, 'w') as f:
                f.write(new_content)

            # Hyprctl ile reload
            subprocess.run(['hyprctl', 'reload'], capture_output=True)
            print("  Hyprland tema uygulandı ve reload edildi")
            return True

        except Exception as e:
            print(f"  Hyprland tema uygulama hatası: {e}")
            return False

    def apply_waybar_theme(self):
        """Waybar temasını uygula - style.css'deki renk değişkenlerini güncelle"""
        style_path = f"{self.config_path}/waybar/style.css"

        try:
            if not os.path.exists(style_path):
                print(f"  Waybar style.css bulunamadı: {style_path}")
                return False

            with open(style_path, 'r') as f:
                content = f.read()

            # Renk değişkenlerini güncelle
            import re
            color_mappings = {
                'bg': self.palette['bg'],
                'bg0': self.palette.get('bg0', self.palette['bg']),
                'bg1': self.palette.get('bg1', self.palette['bg']),
                'bg2': self.palette['bg2'],
                'fg': self.palette['fg'],
                'red': self.palette['red'],
                'orange': self.palette['orange'],
                'yellow': self.palette['yellow'],
                'green': self.palette['green'],
                'aqua': self.palette['aqua'],
                'blue': self.palette['blue'],
                'purple': self.palette['purple'],
                'gray': self.palette.get('gray', self.palette['fg']),
            }

            for color_name, color_value in color_mappings.items():
                # @define-color name #hex; formatını güncelle
                pattern = rf'(@define-color\s+{color_name}\s+)#[0-9a-fA-F]{{6}};'
                replacement = rf'\g<1>{color_value};'
                content = re.sub(pattern, replacement, content)

            with open(style_path, 'w') as f:
                f.write(content)

            print(f"  Waybar style.css güncellendi")

            # Waybar'ı yeniden başlat
            subprocess.run(['pkill', 'waybar'], capture_output=True)
            subprocess.Popen(['waybar'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("  Waybar yeniden başlatıldı")
            return True

        except Exception as e:
            print(f"  Waybar tema uygulama hatası: {e}")
            return False

    def apply_kitty_theme(self):
        """Kitty temasını uygula - renkleri doğrudan kitty.conf'ta güncelle"""
        kitty_conf = f"{self.config_path}/kitty/kitty.conf"

        try:
            if not os.path.exists(kitty_conf):
                print(f"  Kitty config bulunamadı: {kitty_conf}")
                return False

            with open(kitty_conf, 'r') as f:
                content = f.read()

            import re

            # Kitty renk değişkenlerini güncelle
            color_mappings = {
                'background': self.palette['bg'],
                'foreground': self.palette['fg'],
                'cursor': self.palette['fg'],
                'cursor_text_color': self.palette['bg'],
                'selection_foreground': self.palette['bg'],
                'selection_background': self.palette['fg'],
                'color0': self.palette['bg'],      # black
                'color8': self.palette['bg2'],     # bright black
                'color1': self.palette['red'],     # red
                'color9': self.palette['red'],     # bright red
                'color2': self.palette['green'],   # green
                'color10': self.palette['green'],  # bright green
                'color3': self.palette['yellow'],  # yellow
                'color11': self.palette['yellow'], # bright yellow
                'color4': self.palette['blue'],    # blue
                'color12': self.palette['blue'],   # bright blue
                'color5': self.palette['purple'],  # magenta
                'color13': self.palette['purple'], # bright magenta
                'color6': self.palette['aqua'],    # cyan
                'color14': self.palette['aqua'],   # bright cyan
                'color7': self.palette['fg'],      # white
                'color15': self.palette['fg'],     # bright white
            }

            for color_name, color_value in color_mappings.items():
                # "color_name #hex" formatını güncelle
                pattern = rf'^({color_name}\s+)#[0-9a-fA-F]{{6}}'
                replacement = rf'\g<1>{color_value}'
                content = re.sub(pattern, replacement, content, flags=re.MULTILINE)

            # include satırını da ekle/güncelle
            include_line = f"include themes/{self.theme_name}.conf"
            
            # Eski wallpaper include'larını kaldır
            lines = content.split('\n')
            new_lines = [line for line in lines if not ('include' in line and 'themes/wallpaper_' in line)]
            content = '\n'.join(new_lines)

            with open(kitty_conf, 'w') as f:
                f.write(content)

            print("  Kitty kitty.conf renkleri güncellendi")
            return True

        except Exception as e:
            print(f"  Kitty tema uygulama hatası: {e}")
            return False

    def apply_all_themes(self, hyprland=True, waybar=True, kitty=True, rofi=True):
        """Seçili temaları uygula"""
        print(f"\n Temalar uygulanıyor...")

        results = {}

        if hyprland:
            results['hyprland'] = self.apply_hyprland_theme()

        if waybar:
            results['waybar'] = self.apply_waybar_theme()

        if kitty:
            results['kitty'] = self.apply_kitty_theme()

        if rofi:
            results['rofi'] = self.apply_rofi_theme()

        # Wlogout'u güncelle
        results['wlogout'] = self.apply_wlogout_theme()

        # SwayNC'yi güncelle
        results['swaync'] = self.apply_swaync_theme()

        # Hyprlock'u güncelle
        results['hyprlock'] = self.apply_hyprlock_theme()

        # Fastfetch'i güncelle
        results['fastfetch'] = self.apply_fastfetch_theme()

        # GTK (file manager) tema ayarlarını güncelle
        results['gtk'] = self.apply_gtk_theme()

        # Rofi powermenu'yü güncelle
        results['powermenu'] = self.apply_powermenu_theme()

        # Kishi Settings uygulamasını güncelle
        results['kishi_settings'] = self.apply_kishi_settings_theme()

        print(f" Tema uygulama tamamlandı!\n")
        return results

    def apply_powermenu_theme(self):
        """Rofi powermenu temalarını güncelle (SUPER+L)"""
        powermenu_dir = f"{self.config_path}/rofi/powermenu"
        
        try:
            if not os.path.exists(powermenu_dir):
                print(f"  Powermenu dizini bulunamadı: {powermenu_dir}")
                return False

            import re
            updated_count = 0

            # Tüm powermenu type klasörlerini tara
            for type_folder in os.listdir(powermenu_dir):
                type_path = os.path.join(powermenu_dir, type_folder)
                if not os.path.isdir(type_path):
                    continue

                # Her style dosyasını güncelle
                for style_file in os.listdir(type_path):
                    if style_file.endswith('.rasi'):
                        style_path = os.path.join(type_path, style_file)
                        self._update_rofi_style_file(style_path)
                        updated_count += 1

            print(f"  Powermenu: {updated_count} stil dosyası güncellendi")
            return True

        except Exception as e:
            print(f"  Powermenu tema uygulama hatası: {e}")
            return False

    def _update_rofi_style_file(self, style_path):
        """Tek bir rofi stil dosyasını güncelle"""
        import re
        
        try:
            with open(style_path, 'r') as f:
                content = f.read()

            # Renk tanımlamalarını güncelle
            color_mappings = {
                'background': self.palette['bg'],
                'background-alt': self.palette['bg2'],
                'foreground': self.palette['fg'],
                'selected': self.palette['yellow'],
                'active': self.palette['green'],
                'urgent': self.palette['red'],
            }

            for color_name, color_value in color_mappings.items():
                # "name: #XXXXXX;" formatını güncelle
                pattern = rf'({color_name}:\s*)#[0-9a-fA-F]{{6}};?'
                replacement = rf'\g<1>{color_value};'
                content = re.sub(pattern, replacement, content)

            with open(style_path, 'w') as f:
                f.write(content)

        except Exception as e:
            print(f"    Hata ({style_path}): {e}")

    def apply_rofi_theme(self):
        """Rofi temasını uygula - launcher.rasi'deki renk değişkenlerini güncelle"""
        launcher_path = f"{self.config_path}/rofi/launcher.rasi"

        try:
            if not os.path.exists(launcher_path):
                print(f"  Rofi launcher.rasi bulunamadı: {launcher_path}")
                return False

            with open(launcher_path, 'r') as f:
                content = f.read()

            import re
            # Rofi'deki renk tanımlamalarını güncelle (background: #hex; formatı)
            color_mappings = {
                'background': self.palette['bg'],
                'background-alt': self.palette['bg2'],
                'foreground': self.palette['fg'],
                'selected': self.palette['yellow'],
                'active': self.palette['green'],
                'urgent': self.palette['red'],
            }

            for color_name, color_value in color_mappings.items():
                # "name: #hex;" formatını güncelle
                pattern = rf'({color_name}:\s*)#[0-9a-fA-F]{{6}};'
                replacement = rf'\g<1>{color_value};'
                content = re.sub(pattern, replacement, content)

            with open(launcher_path, 'w') as f:
                f.write(content)

            print(f"  Rofi launcher.rasi güncellendi")
            return True

        except Exception as e:
            print(f"  Rofi tema uygulama hatası: {e}")
            return False

    def apply_wlogout_theme(self):
        """Wlogout temasını uygula - style.css'deki renkleri güncelle"""
        wlogout_style = f"{self.config_path}/wlogout/style.css"

        try:
            if not os.path.exists(wlogout_style):
                print(f"  Wlogout style.css bulunamadı: {wlogout_style}")
                return False

            with open(wlogout_style, 'r') as f:
                content = f.read()

            import re
            
            # Wlogout'taki renkleri güncelle
            # background-color: rgba(40, 40, 40, 0.85) -> yeni bg rengi
            bg_rgb = self._hex_to_rgb(self.palette['bg'])
            content = re.sub(
                r'background-color:\s*rgba\(\d+,\s*\d+,\s*\d+,\s*[\d.]+\)',
                f'background-color: rgba({bg_rgb[0]}, {bg_rgb[1]}, {bg_rgb[2]}, 0.85)',
                content
            )

            # background-color: #hex -> yeni bg rengi
            content = re.sub(
                r'(button\s*\{[^}]*background-color:\s*)#[0-9a-fA-F]{6}',
                rf'\g<1>{self.palette["bg"]}',
                content,
                flags=re.DOTALL
            )

            # color: #ebdbb2 -> yeni fg rengi  
            content = re.sub(
                r'(color:\s*)#ebdbb2',
                rf'\g<1>{self.palette["fg"]}',
                content
            )

            # border: 3px solid #hex -> yeni accent rengi
            content = re.sub(
                r'(border:\s*\d+px\s+solid\s+)#[0-9a-fA-F]{6}',
                rf'\g<1>{self.palette["yellow"]}',
                content
            )

            # button:hover background-color
            content = re.sub(
                r'(button:hover\s*\{[^}]*background-color:\s*)#[0-9a-fA-F]{6}',
                rf'\g<1>{self.palette["yellow"]}',
                content,
                flags=re.DOTALL
            )

            with open(wlogout_style, 'w') as f:
                f.write(content)

            print(f"  Wlogout style.css güncellendi")
            return True

        except Exception as e:
            print(f"  Wlogout tema uygulama hatası: {e}")
            return False

    def apply_swaync_theme(self):
        """SwayNC temasını uygula - style.css'deki CSS değişkenlerini güncelle"""
        swaync_style = f"{self.config_path}/swaync/style.css"

        try:
            if not os.path.exists(swaync_style):
                print(f"  SwayNC style.css bulunamadı: {swaync_style}")
                return False

            with open(swaync_style, 'r') as f:
                content = f.read()

            import re
            
            # CSS değişkenlerini güncelle
            bg_rgb = self._hex_to_rgb(self.palette['bg'])
            bg2_rgb = self._hex_to_rgb(self.palette['bg2'])
            
            css_var_mappings = {
                '--bg-1': f'#{self.palette["bg"][1:]}90',  # %90 opacity
                '--bg-2': f'#{self.palette["bg2"][1:]}90',
                '--bg-btn': self.palette['bg2'],
                '--bg-btn-hover': self.palette.get('bg1', self.palette['bg2']),
                '--text': self.palette['fg'],
                '--border': self.palette['bg2'],
                '--pri-low': self.palette['fg'],
                '--pri-normal': self.palette['blue'],
                '--pri-critical': self.palette['red'],
            }

            for var_name, var_value in css_var_mappings.items():
                # --var-name: #hex; formatını güncelle
                pattern = rf'({re.escape(var_name)}:\s*)#[0-9a-fA-F]{{6,8}};?'
                replacement = rf'\g<1>{var_value};'
                content = re.sub(pattern, replacement, content)

            with open(swaync_style, 'w') as f:
                f.write(content)

            # SwayNC'yi yeniden başlat
            subprocess.run(['swaync-client', '-rs'], capture_output=True)
            print(f"  SwayNC style.css güncellendi ve yeniden yüklendi")
            return True

        except Exception as e:
            print(f"  SwayNC tema uygulama hatası: {e}")
            return False

    def apply_hyprlock_theme(self):
        """Hyprlock temasını uygula - colors.conf'u güncelle"""
        hyprlock_colors = f"{self.config_path}/hypr/hyprlock/colors.conf"

        try:
            if not os.path.exists(hyprlock_colors):
                print(f"  Hyprlock colors.conf bulunamadı: {hyprlock_colors}")
                return False

            # Hex'ten rgba formatına çevir
            def hex_to_rgba(hex_color, alpha='ff'):
                hex_clean = hex_color.lstrip('#')
                return f"rgba({hex_clean}{alpha})"

            # Yeni colors.conf içeriği oluştur
            new_content = f"""# Generated by Kishi Settings from wallpaper: {self.wallpaper_name}

# Yazı Rengi
$text_color = {hex_to_rgba(self.palette['fg'])}

# Şifre Girilen Kutunun Arka Planı (Hafif Saydam)
$entry_background_color = {hex_to_rgba(self.palette['bg'], 'ee')}

# Kutunun Kenarlık Rengi (Vurgu)
$entry_border_color = {hex_to_rgba(self.palette['yellow'])}

# Girilen Şifrenin Rengi
$entry_color = {hex_to_rgba(self.palette['fg'])}

# Yazı Tipleri
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font Bold
$font_material_symbols = JetBrainsMono Nerd Font
"""

            with open(hyprlock_colors, 'w') as f:
                f.write(new_content)

            print(f"  Hyprlock colors.conf güncellendi")
            return True

        except Exception as e:
            print(f"  Hyprlock tema uygulama hatası: {e}")
            return False

    def _hex_to_rgb(self, hex_color):
        """Hex rengi RGB tuple'a çevir"""
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

    def apply_fastfetch_theme(self):
        """Fastfetch config'ini güncelle"""
        fastfetch_config = f"{self.config_path}/fastfetch/config.jsonc"
        
        try:
            if not os.path.exists(fastfetch_config):
                print(f"  Fastfetch config bulunamadı: {fastfetch_config}")
                return False

            import json
            import re

            with open(fastfetch_config, 'r') as f:
                content = f.read()

            # Renk isimlerini belirle (light mode için farklı renkler)
            bg_brightness = self._get_brightness_from_hex(self.palette['bg'])
            is_light = bg_brightness > 180  # Açık arka plan mı?
            
            # Fastfetch için uygun renk adı seç
            # Light mode'da koyu renkler, dark mode'da açık renkler
            if is_light:
                main_color = "black"  # Light mode'da siyah yazı
                key_color = "blue"
            else:
                main_color = "yellow"  # Dark mode'da sarı yazı
                key_color = "yellow"

            # display.color değerini güncelle
            content = re.sub(
                r'("color":\s*")[^"]+(")',
                rf'\g<1>{main_color}\2',
                content
            )

            # keyColor değerlerini güncelle
            content = re.sub(
                r'("keyColor":\s*")[^"]+(")',
                rf'\g<1>{key_color}\2',
                content
            )

            with open(fastfetch_config, 'w') as f:
                f.write(content)

            print(f"  Fastfetch config güncellendi (color: {main_color})")
            return True

        except Exception as e:
            print(f"  Fastfetch tema uygulama hatası: {e}")
            return False

    def apply_gtk_theme(self):
        """GTK3 ve GTK4 tema ayarlarını güncelle (dark/light mode)"""
        gtk3_settings = f"{self.config_path}/gtk-3.0/settings.ini"
        gtk4_settings = f"{self.config_path}/gtk-4.0/settings.ini"

        try:
            # Light mode durumu - self.light_mode kullan
            prefer_dark = "0" if self.light_mode else "1"
            
            # GTK3 güncelle
            if os.path.exists(gtk3_settings):
                self._update_gtk_settings(gtk3_settings, prefer_dark)
                print(f"  GTK3 settings güncellendi (dark: {prefer_dark})")

            # GTK4 güncelle
            if os.path.exists(gtk4_settings):
                self._update_gtk_settings(gtk4_settings, prefer_dark)
                print(f"  GTK4 settings güncellendi (dark: {prefer_dark})")

            return True

        except Exception as e:
            print(f"  GTK tema uygulama hatası: {e}")
            return False

    def _update_gtk_settings(self, settings_path, prefer_dark):
        """GTK settings.ini dosyasını güncelle"""
        import re
        
        with open(settings_path, 'r') as f:
            content = f.read()

        # gtk-application-prefer-dark-theme değerini güncelle
        content = re.sub(
            r'(gtk-application-prefer-dark-theme\s*=\s*)\d',
            rf'\g<1>{prefer_dark}',
            content
        )

        with open(settings_path, 'w') as f:
            f.write(content)

    def _get_brightness_from_hex(self, hex_color):
        """Hex renkten brightness hesapla (0-255)"""
        rgb = self._hex_to_rgb(hex_color)
        return int(0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2])

    def apply_kishi_settings_theme(self):
        """Kishi Settings uygulamasının kendi temasını güncelle"""
        # Kishi Settings'in CSS dosya yolu
        kishi_css_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), 
            "style.css"
        )

        try:
            # Light mode durumu - artık self.light_mode kullanılıyor
            is_light = self.light_mode

            # Light mode için kontrast renkleri
            if is_light:
                # Light mode - koyu yazılar, açık arka planlar
                text_color = "#1d1d1d"
                text_secondary = "#505050"
                sidebar_text = "#2d2d2d"
                button_text = "#ffffff"
                view_bg = self.palette['bg']
                card_bg = self.palette['bg1']
                row_bg = self.palette['bg2']
                boxed_list_bg = self.palette['bg1']
            else:
                # Dark mode - açık yazılar, koyu arka planlar
                text_color = self.palette['fg']
                text_secondary = self.palette['fg']
                sidebar_text = self.palette['fg']
                button_text = self.palette['fg']
                view_bg = self.palette['bg']
                card_bg = self.palette['bg1']
                row_bg = self.palette['bg2']
                boxed_list_bg = self.palette['bg1']

            # CSS içeriği oluştur
            css_content = f"""/* Kishi Settings Dynamic Theme */
/* Auto-generated from wallpaper: {self.wallpaper_name} */
/* Mode: {"Light" if is_light else "Dark"} */

/* Renk değişkenleri */
@define-color kishi_bg {self.palette['bg']};
@define-color kishi_bg0 {self.palette['bg0']};
@define-color kishi_bg1 {self.palette['bg1']};
@define-color kishi_bg2 {self.palette['bg2']};
@define-color kishi_fg {self.palette['fg']};
@define-color kishi_red {self.palette['red']};
@define-color kishi_orange {self.palette['orange']};
@define-color kishi_yellow {self.palette['yellow']};
@define-color kishi_green {self.palette['green']};
@define-color kishi_aqua {self.palette['aqua']};
@define-color kishi_blue {self.palette['blue']};
@define-color kishi_purple {self.palette['purple']};
@define-color text_color {text_color};
@define-color text_secondary {text_secondary};
@define-color card_bg {card_bg};
@define-color row_bg {row_bg};

/* Libadwaita renk override'ları - ÖNEMLİ */
@define-color accent_bg_color {self.palette['blue']};
@define-color accent_fg_color {button_text};
@define-color accent_color {self.palette['blue']};
@define-color view_bg_color {view_bg};
@define-color view_fg_color {text_color};
@define-color window_bg_color {self.palette['bg0']};
@define-color window_fg_color {text_color};
@define-color headerbar_bg_color {self.palette['bg0']};
@define-color headerbar_fg_color {text_color};
@define-color card_bg_color {card_bg};
@define-color card_fg_color {text_color};
@define-color popover_bg_color {card_bg};
@define-color popover_fg_color {text_color};
@define-color dialog_bg_color {card_bg};
@define-color dialog_fg_color {text_color};

/* Ana pencere */
window, window.background {{
    background-color: {self.palette['bg0']};
    color: {text_color};
}}

/* Tüm içerik alanları */
.content, scrolledwindow, viewport {{
    background-color: {self.palette['bg0']};
    color: {text_color};
}}

/* PreferencesGroup - Ana kart container */
preferencesgroup {{
    background-color: transparent;
    color: {text_color};
}}

preferencesgroup > box {{
    background-color: transparent;
}}

preferencesgroup > box > label {{
    color: {text_color};
}}

/* Boxed List - Kart içindeki liste */
list.boxed-list {{
    background-color: {boxed_list_bg};
    border-radius: 12px;
}}

list.boxed-list > row {{
    background-color: {row_bg};
    color: {text_color};
}}

list.boxed-list > row:first-child {{
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
}}

list.boxed-list > row:last-child {{
    border-bottom-left-radius: 12px;
    border-bottom-right-radius: 12px;
}}

/* ActionRow - Her satır */
row.activatable {{
    background-color: {row_bg};
    color: {text_color};
}}

row.activatable:hover {{
    background-color: alpha({text_color}, 0.05);
}}

row {{
    color: {text_color};
    background-color: {row_bg};
}}

/* Row içindeki tüm yazılar */
row label, row .title, row .subtitle {{
    color: {text_color};
}}

row .subtitle {{
    color: {text_secondary};
}}

/* Card stilleri */
.card {{
    background-color: {card_bg};
    border-radius: 12px;
    color: {text_color};
}}

/* FlowBox (wallpaper grid) */
flowboxchild {{
    border-radius: 8px;
    padding: 5px;
}}

flowboxchild:selected {{
    background-color: alpha({self.palette['blue']}, 0.3);
    border: 2px solid {self.palette['blue']};
}}

/* Headerbar */
headerbar {{
    background-color: {self.palette['bg0']};
    color: {text_color};
}}

headerbar * {{
    color: {text_color};
}}

/* Sidebar */
.navigation-sidebar {{
    background-color: {self.palette['bg']};
    color: {sidebar_text};
}}

.navigation-sidebar row {{
    color: {sidebar_text};
    background-color: transparent;
}}

.navigation-sidebar row:selected {{
    background-color: alpha({self.palette['blue']}, 0.25);
}}

.navigation-sidebar row label {{
    color: {sidebar_text};
}}

/* SpinRow ve diğer özel satırlar */
spinrow, spinrow > box {{
    background-color: {row_bg};
    color: {text_color};
}}

/* SpinButton */
spinbutton {{
    background-color: alpha({text_color}, 0.1);
    color: {text_color};
}}

spinbutton text {{
    color: {text_color};
}}

spinbutton button {{
    color: {text_color};
}}

/* Butonlar */
button {{
    color: {text_color};
}}

button.suggested-action {{
    background-color: {self.palette['blue']};
    color: {button_text};
}}

button.destructive-action {{
    background-color: {self.palette['red']};
    color: {button_text};
}}

button.circular {{
    color: {text_color};
}}

/* Toggle butonlar */
togglebutton {{
    color: {text_color};
}}

togglebutton:checked {{
    background-color: alpha({self.palette['blue']}, 0.3);
    color: {text_color};
}}

/* Switch */
switch {{
    background-color: alpha({text_color}, 0.2);
}}

switch:checked {{
    background-color: {self.palette['green']};
}}

/* Scale (Slider) */
scale trough {{
    background-color: alpha({text_color}, 0.2);
}}

scale trough highlight {{
    background-color: {self.palette['blue']};
}}

scale slider {{
    background-color: {self.palette['fg'] if not is_light else '#ffffff'};
}}

/* Entry */
entry {{
    background-color: alpha({text_color}, 0.1);
    color: {text_color};
}}

entry text {{
    color: {text_color};
}}

/* Labels - genel */
label {{
    color: {text_color};
}}

/* Progress bar */
progressbar > trough > progress {{
    background-color: {self.palette['blue']};
}}

/* Scrollbar */
scrollbar slider {{
    background-color: alpha({text_color}, 0.3);
}}

scrollbar slider:hover {{
    background-color: alpha({self.palette['blue']}, 0.5);
}}

/* ExpanderRow */
row.expander {{
    background-color: {row_bg};
    color: {text_color};
}}

row.expander list {{
    background-color: {card_bg};
}}

row.expander image.expander-row-arrow {{
    color: {text_color};
}}
"""
            # CSS dosyasına yaz
            with open(kishi_css_path, 'w') as f:
                f.write(css_content)

            print(f"  Kishi Settings teması güncellendi ({"Light" if is_light else "Dark"} mode)")
            return True

        except Exception as e:
            print(f"  Kishi Settings tema uygulama hatası: {e}")
            return False
