# Gruvbox Teması Renk Tanımları

# Yazı Rengi (Bej)
$text_color = rgba(ebdbb2ff)

# Şifre Girilen Kutunun Arka Planı (Koyu Gri - Hafif Saydam)
$entry_background_color = rgba(282828ee)

# Kutunun Kenarlık Rengi (Turuncu/Sarı - Vurgu)
$entry_border_color = rgba(d79921ff)

# Girilen Şifrenin Rengi (Bej)
$entry_color = rgba(ebdbb2ff)

# Yazı Tipleri (Sistemin kalanıyla aynı)
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font Bold
$font_material_symbols = JetBrainsMono Nerd Font
